# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Directory Directory
email: github@olliepalmer.com
description: >- # this means to ignore newlines until "baseurl:"
  The Directory Directory:
  The one and only convenient directory for all your needs
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _olliepalmer
github_username:  olliepalmer

# Build settings
theme: "just-the-docs"
plugins:
  - jekyll-feed

footer_content:
  "Copyright &copy; 2019 Ollie Palmer. Site content distributed under an
  <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\" target=\"_blank\">MIT license</a>
  (you are free to reuse content as you like). Initially generated for
  <a href=\"https://github.com/NaNoGenMo/2019\" target=\"_blank\">NaNoGenMo 2019</a>;
  all code to generate content and this website available on
  <a href=\"https://github.com/olliepalmer/nanogenmo2019\" target=\"_blank\">GitHub</a>
  This site uses <a href=\"https://github.com/pmarsceill/just-the-docs\" target=\"_blank\">Just the Docs</a>,
  a documentation theme for Jekyll."

search_enabled: true

atom:
  buildCommand:
    - bundle exec jekyll build


# additional links at top-right
# aux_links:
#   "Just the Docs on GitHub":
#     - "//github.com/pmarsceill/just-the-docs"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
